{{- if .Values.rbac.roleBinding.enabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.role.roleBindingName }}
  namespace: {{ .Values.rbac.role.roleNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.role.serviceAccountName }}
    namespace: {{ .Values.rbac.role.roleNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.role.roleName }}
  namespace: {{ .Values.rbac.role.roleBindingNamespace }}
  {{- end }}