apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: validation-role
  namespace: rs1-lpar01-sumd-validation
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: validation-rolebinding
  namespace: rs1-lpar01-sumd-validation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: validation-role
subjects:
  - kind: ServiceAccount
    name: validation-service-account
    namespace: rs1-lpar01-sumd-system